apiVersion: v1
kind: Secret
metadata:
  name: erp-postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erp-postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          envFrom:
            - secretRef:
                name: erp-postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: erp-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
